version: "3.8"

x-common-variables: &common-variables
  MYSQL_DATABASE: books
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql-db:
    image: mysql
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  api:
    image: api:local
    build:
      dockerfile: Dockerfile
      context: server
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 3001:3000

  client:
    image: client:local
    stdin_open: true
    environment:
      - CHOKIDAR_USERPOLLING=true
    build:
      dockerfile: Dockerfile.prod
      context: client
    ports:
      - 3000:3000

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    environment:
      ADMINER_DEFAULT_SERVER: mysql-db
